

export const timezoneMap: Record<string, { timezone: string; country: string }> = {
  // US States and Major Cities
  'alabama': { timezone: 'America/Chicago', country: 'United States' },
  'birmingham': { timezone: 'America/Chicago', country: 'United States' },
  'montgomery': { timezone: 'America/Chicago', country: 'United States' },
  'mobile': { timezone: 'America/Chicago', country: 'United States' },
  'huntsville': { timezone: 'America/Chicago', country: 'United States' },
  'tuscaloosa': { timezone: 'America/Chicago', country: 'United States' },
  'alaska': { timezone: 'America/Anchorage', country: 'United States' },
  'anchorage': { timezone: 'America/Anchorage', country: 'United States' },
  'fairbanks': { timezone: 'America/Anchorage', country: 'United States' },
  'juneau': { timezone: 'America/Anchorage', country: 'United States' },
  'sitka': { timezone: 'America/Anchorage', country: 'United States' },
  'ketchikan': { timezone: 'America/Anchorage', country: 'United States' },
  'arizona': { timezone: 'America/Phoenix', country: 'United States' },
  'phoenix': { timezone: 'America/Phoenix', country: 'United States' },
  'tucson': { timezone: 'America/Phoenix', country: 'United States' },
  'mesa': { timezone: 'America/Phoenix', country: 'United States' },
  'chandler': { timezone: 'America/Phoenix', country: 'United States' },
  'scottsdale': { timezone: 'America/Phoenix', country: 'United States' },
  'arkansas': { timezone: 'America/Chicago', country: 'United States' },
  'little rock': { timezone: 'America/Chicago', country: 'United States' },
  'fort smith': { timezone: 'America/Chicago', country: 'United States' },
  'fayetteville': { timezone: 'America/Chicago', country: 'United States' },
  'springdale': { timezone: 'America/Chicago', country: 'United States' },
  'jonesboro': { timezone: 'America/Chicago', country: 'United States' },
  'california': { timezone: 'America/Los_Angeles', country: 'United States' },
  'los angeles': { timezone: 'America/Los_Angeles', country: 'United States' },
  'san francisco': { timezone: 'America/Los_Angeles', country: 'United States' },
  'san diego': { timezone: 'America/Los_Angeles', country: 'United States' },
  'sacramento': { timezone: 'America/Los_Angeles', country: 'United States' },
  'san jose': { timezone: 'America/Los_Angeles', country: 'United States' },
  'oakland': { timezone: 'America/Los_Angeles', country: 'United States' },
  'fresno': { timezone: 'America/Los_Angeles', country: 'United States' },
  'long beach': { timezone: 'America/Los_Angeles', country: 'United States' },
  'colorado': { timezone: 'America/Denver', country: 'United States' },
  'denver': { timezone: 'America/Denver', country: 'United States' },
  'colorado springs': { timezone: 'America/Denver', country: 'United States' },
  'aurora co': { timezone: 'America/Denver', country: 'United States' },
  'fort collins': { timezone: 'America/Denver', country: 'United States' },
  'lakewood': { timezone: 'America/Denver', country: 'United States' },
  'connecticut': { timezone: 'America/New_York', country: 'United States' },
  'hartford': { timezone: 'America/New_York', country: 'United States' },
  'bridgeport': { timezone: 'America/New_York', country: 'United States' },
  'new haven': { timezone: 'America/New_York', country: 'United States' },
  'waterbury': { timezone: 'America/New_York', country: 'United States' },
  'stamford': { timezone: 'America/New_York', country: 'United States' },
  'delaware': { timezone: 'America/New_York', country: 'United States' },
  'wilmington': { timezone: 'America/New_York', country: 'United States' },
  'dover': { timezone: 'America/New_York', country: 'United States' },
  'newark de': { timezone: 'America/New_York', country: 'United States' },
  'middletown': { timezone: 'America/New_York', country: 'United States' },
  'smyrna': { timezone: 'America/New_York', country: 'United States' },
  'florida': { timezone: 'America/New_York', country: 'United States' },
  'miami': { timezone: 'America/New_York', country: 'United States' },
  'tampa': { timezone: 'America/New_York', country: 'United States' },
  'orlando': { timezone: 'America/New_York', country: 'United States' },
  'jacksonville': { timezone: 'America/New_York', country: 'United States' },
  'fort lauderdale': { timezone: 'America/New_York', country: 'United States' },
  'tallahassee': { timezone: 'America/New_York', country: 'United States' },
  'st. petersburg': { timezone: 'America/New_York', country: 'United States' },
  'georgia': { timezone: 'America/New_York', country: 'United States' },
  'atlanta': { timezone: 'America/New_York', country: 'United States' },
  'columbus ga': { timezone: 'America/New_York', country: 'United States' },
  'augusta': { timezone: 'America/New_York', country: 'United States' },
  'savannah': { timezone: 'America/New_York', country: 'United States' },
  'athens ga': { timezone: 'America/New_York', country: 'United States' },
  'hawaii': { timezone: 'Pacific/Honolulu', country: 'United States' },
  'honolulu': { timezone: 'Pacific/Honolulu', country: 'United States' },
  'hilo': { timezone: 'Pacific/Honolulu', country: 'United States' },
  'kailua-kona': { timezone: 'Pacific/Honolulu', country: 'United States' },
  'kaneohe': { timezone: 'Pacific/Honolulu', country: 'United States' },
  'waipahu': { timezone: 'Pacific/Honolulu', country: 'United States' },
  'idaho': { timezone: 'America/Boise', country: 'United States' },
  'boise': { timezone: 'America/Boise', country: 'United States' },
  'nampa': { timezone: 'America/Boise', country: 'United States' },
  'meridian': { timezone: 'America/Boise', country: 'United States' },
  'idaho falls': { timezone: 'America/Boise', country: 'United States' },
  'pocatello': { timezone: 'America/Boise', country: 'United States' },
  'illinois': { timezone: 'America/Chicago', country: 'United States' },
  'chicago': { timezone: 'America/Chicago', country: 'United States' },
  'aurora il': { timezone: 'America/Chicago', country: 'United States' },
  'peoria': { timezone: 'America/Chicago', country: 'United States' },
  'rockford': { timezone: 'America/Chicago', country: 'United States' },
  'elgin': { timezone: 'America/Chicago', country: 'United States' },
  'springfield il': { timezone: 'America/Chicago', country: 'United States' },
  'indiana': { timezone: 'America/Indiana/Indianapolis', country: 'United States' },
  'indianapolis': { timezone: 'America/Indiana/Indianapolis', country: 'United States' },
  'fort wayne': { timezone: 'America/Indiana/Indianapolis', country: 'United States' },
  'evansville': { timezone: 'America/Indiana/Indianapolis', country: 'United States' },
  'south bend': { timezone: 'America/Indiana/Indianapolis', country: 'United States' },
  'carmel': { timezone: 'America/Indiana/Indianapolis', country: 'United States' },
  'iowa': { timezone: 'America/Chicago', country: 'United States' },
  'des moines': { timezone: 'America/Chicago', country: 'United States' },
  'cedar rapids': { timezone: 'America/Chicago', country: 'United States' },
  'davenport': { timezone: 'America/Chicago', country: 'United States' },
  'sioux city': { timezone: 'America/Chicago', country: 'United States' },
  'iowa city': { timezone: 'America/Chicago', country: 'United States' },
  'kansas': { timezone: 'America/Chicago', country: 'United States' },
  'wichita': { timezone: 'America/Chicago', country: 'United States' },
  'overland park': { timezone: 'America/Chicago', country: 'United States' },
  'kansas city': { timezone: 'America/Chicago', country: 'United States' },
  'olathe': { timezone: 'America/Chicago', country: 'United States' },
  'topeka': { timezone: 'America/Chicago', country: 'United States' },
  'kentucky': { timezone: 'America/New_York', country: 'United States' },
  'louisville': { timezone: 'America/New_York', country: 'United States' },
  'lexington': { timezone: 'America/New_York', country: 'United States' },
  'bowling green': { timezone: 'America/New_York', country: 'United States' },
  'owensboro': { timezone: 'America/New_York', country: 'United States' },
  'covington': { timezone: 'America/New_York', country: 'United States' },
  'louisiana': { timezone: 'America/Chicago', country: 'United States' },
  'new orleans': { timezone: 'America/Chicago', country: 'United States' },
  'baton rouge': { timezone: 'America/Chicago', country: 'United States' },
  'shreveport': { timezone: 'America/Chicago', country: 'United States' },
  'lafayette': { timezone: 'America/Chicago', country: 'United States' },
  'lake charles': { timezone: 'America/Chicago', country: 'United States' },
  'maine': { timezone: 'America/New_York', country: 'United States' },
  'portland me': { timezone: 'America/New_York', country: 'United States' },
  'lewiston': { timezone: 'America/New_York', country: 'United States' },
  'bangor': { timezone: 'America/New_York', country: 'United States' },
  'south portland': { timezone: 'America/New_York', country: 'United States' },
  'auburn': { timezone: 'America/New_York', country: 'United States' },
  'maryland': { timezone: 'America/New_York', country: 'United States' },
  'baltimore': { timezone: 'America/New_York', country: 'United States' },
  'frederick': { timezone: 'America/New_York', country: 'United States' },
  'rockville': { timezone: 'America/New_York', country: 'United States' },
  'gaithersburg': { timezone: 'America/New_York', country: 'United States' },
  'bowie': { timezone: 'America/New_York', country: 'United States' },
  'massachusetts': { timezone: 'America/New_York', country: 'United States' },
  'boston': { timezone: 'America/New_York', country: 'United States' },
  'worcester': { timezone: 'America/New_York', country: 'United States' },
  'springfield ma': { timezone: 'America/New_York', country: 'United States' },
  'cambridge': { timezone: 'America/New_York', country: 'United States' },
  'lowell': { timezone: 'America/New_York', country: 'United States' },
  'michigan': { timezone: 'America/Detroit', country: 'United States' },
  'detroit': { timezone: 'America/Detroit', country: 'United States' },
  'grand rapids': { timezone: 'America/Detroit', country: 'United States' },
  'warren': { timezone: 'America/Detroit', country: 'United States' },
  'sterling heights': { timezone: 'America/Detroit', country: 'United States' },
  'lansing': { timezone: 'America/Detroit', country: 'United States' },
  'minnesota': { timezone: 'America/Chicago', country: 'United States' },
  'minneapolis': { timezone: 'America/Chicago', country: 'United States' },
  'saint paul': { timezone: 'America/Chicago', country: 'United States' },
  'rochester mn': { timezone: 'America/Chicago', country: 'United States' },
  'duluth': { timezone: 'America/Chicago', country: 'United States' },
  'bloomington': { timezone: 'America/Chicago', country: 'United States' },
  'mississippi': { timezone: 'America/Chicago', country: 'United States' },
  'jackson': { timezone: 'America/Chicago', country: 'United States' },
  'gulfport': { timezone: 'America/Chicago', country: 'United States' },
  'southaven': { timezone: 'America/Chicago', country: 'United States' },
  'hattiesburg': { timezone: 'America/Chicago', country: 'United States' },
  'biloxi': { timezone: 'America/Chicago', country: 'United States' },
  'missouri': { timezone: 'America/Chicago', country: 'United States' },
  'st louis': { timezone: 'America/Chicago', country: 'United States' },
  'columbia mo': { timezone: 'America/Chicago', country: 'United States' },
  'independence': { timezone: 'America/Chicago', country: 'United States' },
  'montana': { timezone: 'America/Denver', country: 'United States' },
  'billings': { timezone: 'America/Denver', country: 'United States' },
  'missoula': { timezone: 'America/Denver', country: 'United States' },
  'great falls': { timezone: 'America/Denver', country: 'United States' },
  'bozeman': { timezone: 'America/Denver', country: 'United States' },
  'helena': { timezone: 'America/Denver', country: 'United States' },
  'nebraska': { timezone: 'America/Chicago', country: 'United States' },
  'omaha': { timezone: 'America/Chicago', country: 'United States' },
  'lincoln': { timezone: 'America/Chicago', country: 'United States' },
  'bellevue': { timezone: 'America/Chicago', country: 'United States' },
  'grand island': { timezone: 'America/Chicago', country: 'United States' },
  'kearney': { timezone: 'America/Chicago', country: 'United States' },
  'nevada': { timezone: 'America/Los_Angeles', country: 'United States' },
  'las vegas': { timezone: 'America/Los_Angeles', country: 'United States' },
  'henderson': { timezone: 'America/Los_Angeles', country: 'United States' },
  'reno': { timezone: 'America/Los_Angeles', country: 'United States' },
  'north las vegas': { timezone: 'America/Los_Angeles', country: 'United States' },
  'sparks': { timezone: 'America/Los_Angeles', country: 'United States' },
  'new hampshire': { timezone: 'America/New_York', country: 'United States' },
  'manchester': { timezone: 'America/New_York', country: 'United States' },
  'nashua': { timezone: 'America/New_York', country: 'United States' },
  'concord': { timezone: 'America/New_York', country: 'United States' },
  'derry': { timezone: 'America/New_York', country: 'United States' },
  'rochester nh': { timezone: 'America/New_York', country: 'United States' },
  'new jersey': { timezone: 'America/New_York', country: 'United States' },
  'newark nj': { timezone: 'America/New_York', country: 'United States' },
  'jersey city': { timezone: 'America/New_York', country: 'United States' },
  'paterson': { timezone: 'America/New_York', country: 'United States' },
  'elizabeth': { timezone: 'America/New_York', country: 'United States' },
  'edison': { timezone: 'America/New_York', country: 'United States' },
  'new mexico': { timezone: 'America/Denver', country: 'United States' },
  'albuquerque': { timezone: 'America/Denver', country: 'United States' },
  'las cruces': { timezone: 'America/Denver', country: 'United States' },
  'rio rancho': { timezone: 'America/Denver', country: 'United States' },
  'santa fe': { timezone: 'America/Denver', country: 'United States' },
  'roswell': { timezone: 'America/Denver', country: 'United States' },
  'new york': { timezone: 'America/New_York', country: 'United States' },
  'new york city': { timezone: 'America/New_York', country: 'United States' },
  'buffalo': { timezone: 'America/New_York', country: 'United States' },
  'rochester ny': { timezone: 'America/New_York', country: 'United States' },
  'yonkers': { timezone: 'America/New_York', country: 'United States' },
  'syracuse': { timezone: 'America/New_York', country: 'United States' },
  'albany': { timezone: 'America/New_York', country: 'United States' },
  'north carolina': { timezone: 'America/New_York', country: 'United States' },
  'charlotte': { timezone: 'America/New_York', country: 'United States' },
  'raleigh': { timezone: 'America/New_York', country: 'United States' },
  'greensboro': { timezone: 'America/New_York', country: 'United States' },
  'durham': { timezone: 'America/New_York', country: 'United States' },
  'winston-salem': { timezone: 'America/New_York', country: 'United States' },
  'north dakota': { timezone: 'America/Chicago', country: 'United States' },
  'fargo': { timezone: 'America/Chicago', country: 'United States' },
  'bismarck': { timezone: 'America/Chicago', country: 'United States' },
  'grand forks': { timezone: 'America/Chicago', country: 'United States' },
  'minot': { timezone: 'America/Chicago', country: 'United States' },
  'west fargo': { timezone: 'America/Chicago', country: 'United States' },
  'ohio': { timezone: 'America/New_York', country: 'United States' },
  'columbus oh': { timezone: 'America/New_York', country: 'United States' },
  'cleveland': { timezone: 'America/New_York', country: 'United States' },
  'cincinnati': { timezone: 'America/New_York', country: 'United States' },
  'toledo': { timezone: 'America/New_York', country: 'United States' },
  'akron': { timezone: 'America/New_York', country: 'United States' },
  'oklahoma': { timezone: 'America/Chicago', country: 'United States' },
  'oklahoma city': { timezone: 'America/Chicago', country: 'United States' },
  'tulsa': { timezone: 'America/Chicago', country: 'United States' },
  'norman': { timezone: 'America/Chicago', country: 'United States' },
  'broken arrow': { timezone: 'America/Chicago', country: 'United States' },
  'lawton': { timezone: 'America/Chicago', country: 'United States' },
  'oregon': { timezone: 'America/Los_Angeles', country: 'United States' },
  'portland or': { timezone: 'America/Los_Angeles', country: 'United States' },
  'eugene': { timezone: 'America/Los_Angeles', country: 'United States' },
  'salem': { timezone: 'America/Los_Angeles', country: 'United States' },
  'gresham': { timezone: 'America/Los_Angeles', country: 'United States' },
  'hillsboro': { timezone: 'America/Los_Angeles', country: 'United States' },
  'pennsylvania': { timezone: 'America/New_York', country: 'United States' },
  'philadelphia': { timezone: 'America/New_York', country: 'United States' },
  'pittsburgh': { timezone: 'America/New_York', country: 'United States' },
  'allentown': { timezone: 'America/New_York', country: 'United States' },
  'erie': { timezone: 'America/New_York', country: 'United States' },
  'reading': { timezone: 'America/New_York', country: 'United States' },
  'rhode island': { timezone: 'America/New_York', country: 'United States' },
  'providence': { timezone: 'America/New_York', country: 'United States' },
  'warwick': { timezone: 'America/New_York', country: 'United States' },
  'cranston': { timezone: 'America/New_York', country: 'United States' },
  'pawtucket': { timezone: 'America/New_York', country: 'United States' },
  'east providence': { timezone: 'America/New_York', country: 'United States' },
  'south carolina': { timezone: 'America/New_York', country: 'United States' },
  'charleston': { timezone: 'America/New_York', country: 'United States' },
  'columbia sc': { timezone: 'America/New_York', country: 'United States' },
  'north charleston': { timezone: 'America/New_York', country: 'United States' },
  'mount pleasant': { timezone: 'America/New_York', country: 'United States' },
  'rock hill': { timezone: 'America/New_York', country: 'United States' },
  'south dakota': { timezone: 'America/Chicago', country: 'United States' },
  'sioux falls': { timezone: 'America/Chicago', country: 'United States' },
  'rapid city': { timezone: 'America/Denver', country: 'United States' },
  'aberdeen': { timezone: 'America/Chicago', country: 'United States' },
  'brookings': { timezone: 'America/Chicago', country: 'United States' },
  'watertown': { timezone: 'America/Chicago', country: 'United States' },
  'tennessee': { timezone: 'America/Chicago', country: 'United States' },
  'nashville': { timezone: 'America/Chicago', country: 'United States' },
  'memphis': { timezone: 'America/Chicago', country: 'United States' },
  'knoxville': { timezone: 'America/New_York', country: 'United States' },
  'chattanooga': { timezone: 'America/New_York', country: 'United States' },
  'clarksville': { timezone: 'America/Chicago', country: 'United States' },
  'texas': { timezone: 'America/Chicago', country: 'United States' },
  'houston': { timezone: 'America/Chicago', country: 'United States' },
  'san antonio': { timezone: 'America/Chicago', country: 'United States' },
  'dallas': { timezone: 'America/Chicago', country: 'United States' },
  'austin': { timezone: 'America/Chicago', country: 'United States' },
  'fort worth': { timezone: 'America/Chicago', country: 'United States' },
  'el paso': { timezone: 'America/Denver', country: 'United States' },
  'arlington': { timezone: 'America/Chicago', country: 'United States' },
  'utah': { timezone: 'America/Denver', country: 'United States' },
  'salt lake city': { timezone: 'America/Denver', country: 'United States' },
  'west valley city': { timezone: 'America/Denver', country: 'United States' },
  'provo': { timezone: 'America/Denver', country: 'United States' },
  'west jordan': { timezone: 'America/Denver', country: 'United States' },
  'orem': { timezone: 'America/Denver', country: 'United States' },
  'vermont': { timezone: 'America/New_York', country: 'United States' },
  'burlington': { timezone: 'America/New_York', country: 'United States' },
  'essex': { timezone: 'America/New_York', country: 'United States' },
  'south burlington': { timezone: 'America/New_York', country: 'United States' },
  'colchester': { timezone: 'America/New_York', country: 'United States' },
  'rutland': { timezone: 'America/New_York', country: 'United States' },
  'virginia': { timezone: 'America/New_York', country: 'United States' },
  'virginia beach': { timezone: 'America/New_York', country: 'United States' },
  'norfolk': { timezone: 'America/New_York', country: 'United States' },
  'chesapeake': { timezone: 'America/New_York', country: 'United States' },
  'richmond': { timezone: 'America/New_York', country: 'United States' },
  'newport news': { timezone: 'America/New_York', country: 'United States' },
  'washington state': { timezone: 'America/Los_Angeles', country: 'United States' },
  'seattle': { timezone: 'America/Los_Angeles', country: 'United States' },
  'spokane': { timezone: 'America/Los_Angeles', country: 'United States' },
  'tacoma': { timezone: 'America/Los_Angeles', country: 'United States' },
  'vancouver wa': { timezone: 'America/Los_Angeles', country: 'United States' },
  'bellevue wa': { timezone: 'America/Los_Angeles', country: 'United States' },
  'west virginia': { timezone: 'America/New_York', country: 'United States' },
  'charleston wv': { timezone: 'America/New_York', country: 'United States' },
  'huntington wv': { timezone: 'America/New_York', country: 'United States' },
  'morgantown': { timezone: 'America/New_York', country: 'United States' },
  'parkersburg': { timezone: 'America/New_York', country: 'United States' },
  'wheeling': { timezone: 'America/New_York', country: 'United States' },
  'wisconsin': { timezone: 'America/Chicago', country: 'United States' },
  'milwaukee': { timezone: 'America/Chicago', country: 'United States' },
  'madison': { timezone: 'America/Chicago', country: 'United States' },
  'green bay': { timezone: 'America/Chicago', country: 'United States' },
  'kenosha': { timezone: 'America/Chicago', country: 'United States' },
  'racine': { timezone: 'America/Chicago', country: 'United States' },
  'wyoming': { timezone: 'America/Denver', country: 'United States' },
  'cheyenne': { timezone: 'America/Denver', country: 'United States' },
  'casper': { timezone: 'America/Denver', country: 'United States' },
  'laramie': { timezone: 'America/Denver', country: 'United States' },
  'gillette': { timezone: 'America/Denver', country: 'United States' },
  'rock springs': { timezone: 'America/Denver', country: 'United States' },
  
  // Washington DC
  'district of columbia': { timezone: 'America/New_York', country: 'United States' },
  'washington': { timezone: 'America/New_York', country: 'United States' },
  'washington dc': { timezone: 'America/New_York', country: 'United States' },
  'dc': { timezone: 'America/New_York', country: 'United States' },
  
  // Major International Cities
  'london': { timezone: 'Europe/London', country: 'United Kingdom' },
  'paris': { timezone: 'Europe/Paris', country: 'France' },
  'berlin': { timezone: 'Europe/Berlin', country: 'Germany' },
  'rome': { timezone: 'Europe/Rome', country: 'Italy' },
  'madrid': { timezone: 'Europe/Madrid', country: 'Spain' },
  'amsterdam': { timezone: 'Europe/Amsterdam', country: 'Netherlands' },
  'zurich': { timezone: 'Europe/Zurich', country: 'Switzerland' },
  'vienna': { timezone: 'Europe/Vienna', country: 'Austria' },
  'stockholm': { timezone: 'Europe/Stockholm', country: 'Sweden' },
  'oslo': { timezone: 'Europe/Oslo', country: 'Norway' },
  'copenhagen': { timezone: 'Europe/Copenhagen', country: 'Denmark' },
  'helsinki': { timezone: 'Europe/Helsinki', country: 'Finland' },
  'warsaw': { timezone: 'Europe/Warsaw', country: 'Poland' },
  'prague': { timezone: 'Europe/Prague', country: 'Czech Republic' },
  'budapest': { timezone: 'Europe/Budapest', country: 'Hungary' },
  'moscow': { timezone: 'Europe/Moscow', country: 'Russia' },
  'istanbul': { timezone: 'Europe/Istanbul', country: 'Turkey' },
  'tokyo': { timezone: 'Asia/Tokyo', country: 'Japan' },
  'seoul': { timezone: 'Asia/Seoul', country: 'South Korea' },
  'beijing': { timezone: 'Asia/Shanghai', country: 'China' },
  'shanghai': { timezone: 'Asia/Shanghai', country: 'China' },
  'hong kong': { timezone: 'Asia/Hong_Kong', country: 'Hong Kong' },
  'singapore': { timezone: 'Asia/Singapore', country: 'Singapore' },
  'bangkok': { timezone: 'Asia/Bangkok', country: 'Thailand' },
  'mumbai': { timezone: 'Asia/Kolkata', country: 'India' },
  'delhi': { timezone: 'Asia/Kolkata', country: 'India' },
  'dubai': { timezone: 'Asia/Dubai', country: 'United Arab Emirates' },
  'sydney': { timezone: 'Australia/Sydney', country: 'Australia' },
  'melbourne': { timezone: 'Australia/Melbourne', country: 'Australia' },
  'brisbane': { timezone: 'Australia/Brisbane', country: 'Australia' },
  'perth': { timezone: 'Australia/Perth', country: 'Australia' },
  'toronto': { timezone: 'America/Toronto', country: 'Canada' },
  'vancouver ca': { timezone: 'America/Vancouver', country: 'Canada' },
  'montreal': { timezone: 'America/Montreal', country: 'Canada' },
  'calgary': { timezone: 'America/Edmonton', country: 'Canada' },
  'ottawa': { timezone: 'America/Toronto', country: 'Canada' },
  'mexico city': { timezone: 'America/Mexico_City', country: 'Mexico' },
  'guadalajara': { timezone: 'America/Mexico_City', country: 'Mexico' },
  'sao paulo': { timezone: 'America/Sao_Paulo', country: 'Brazil' },
  'rio de janeiro': { timezone: 'America/Sao_Paulo', country: 'Brazil' },
  'buenos aires': { timezone: 'America/Argentina/Buenos_Aires', country: 'Argentina' },
  'lima': { timezone: 'America/Lima', country: 'Peru' },
  'bogota': { timezone: 'America/Bogota', country: 'Colombia' },
  'santiago': { timezone: 'America/Santiago', country: 'Chile' },
  'cape town': { timezone: 'Africa/Johannesburg', country: 'South Africa' },
  'johannesburg': { timezone: 'Africa/Johannesburg', country: 'South Africa' },
  'cairo': { timezone: 'Africa/Cairo', country: 'Egypt' },
  'lagos': { timezone: 'Africa/Lagos', country: 'Nigeria' },
  'nairobi': { timezone: 'Africa/Nairobi', country: 'Kenya' }
};

export const popularLocations = [
  { name: "New York, NY", query: "New York" },
  { name: "Los Angeles, CA", query: "Los Angeles" },
  { name: "Chicago, IL", query: "Chicago" },
  { name: "London, UK", query: "London" },
  { name: "Tokyo, Japan", query: "Tokyo" },
  { name: "Sydney, Australia", query: "Sydney" },
  { name: "Dubai, UAE", query: "Dubai" },
  { name: "Paris, France", query: "Paris" }
];

